#!/bin/bash

# Update package databases
sudo pacman -Sy

# Install individual packages
sudo pacman -S steam yay asusctl rog-control-center meson base-devel ninja podman libgudev

# Install steam-deckify using pamac
pamac install steam-deckify

# Install gamescope-plus and its 32-bit version
yay -S gamescope-plus multilib/lib32-gamescope-plus

# Install decky-installer from GitHub
curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh
